version: '3.0'

expectations:
  population_size: 1000

actions:
  diamorphine_issues:
    run: >
      sqlrunner:latest
        analysis/diamorphine.sql
        --output output/medication_counts.csv
        --dummy-data-file analysis/medication_counts.dummy.csv
    outputs:
      moderately_sensitive:
        medication_counts: output/medication_counts.csv
